services:
  - type: web
    name: my-tennis-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn my_tennis_club.wsgi:application"
    staticPublishPath: staticfiles
